update_fastlane

default_platform(:android)

platform :android do
  desc "Runs checks for the build"
  lane :checks do
    android_set_version_code(
      version_code: ENV["TRAVIS_BUILD_NUMBER"],
      gradle_file: "conveyor/build.gradle"
    )
    gradle(task: "clean assembleDebug test ktlintCheck")
    appcenter_upload(
      app_name: "Conveyor",
      apk: "conveyor/build/outputs/apk/debug/conveyor-debug.apk"
    )
    danger
  end
end