update_fastlane

default_platform(:android)

platform :android do
  desc "Used to check that a build passes all necessary checks. runs `clean assembleDebug test detekt lintDebug` "
  lane :checks do
    gradle(task: "clean assembleDebug test detekt lintDebug")
    danger
  end

  desc "Bumps version number and deploys to app center"
  lane :deploy do
    android_set_version_code(
      version_code: ENV["TRAVIS_BUILD_NUMBER"],
      gradle_file: "conveyor/build.gradle"
    )
    gradle(task: "clean assembleDebug")
    appcenter_upload(
      app_name: "Conveyor",
      group: "Collaborators,Public",
      apk: "conveyor/build/outputs/apk/debug/conveyor-debug.apk"
    )
  end
end